### ISSUE TITLE
multiline docstrings are not fully shown when hoovering over symbol

### ISSUE THREAD

**Issue by malkhamis** [MordFustang21/ide-gopls#1]
When hoovering over a symbol, I only see the very first line of the docstring. The expected behaviour is that I see the full docstring, not just the first line of it.

**Comment by MordFustang21** [comment]
Thanks for the issue. This should be able to be turned on by adding the below snippet to your atom config.
```cson
gopls:
    hoverKind: "FullDocumentation"
    usePlaceholders: true
    wantCompletionDocumentation: true
    wantUnimportedCompletions: true
```

Here are some more settings available https://github.com/golang/tools/blob/master/gopls/doc/user.md#settings

**Comment by malkhamis** [comment]
Thanks you for your response.. I am unsure if you were talking about the config.cson file?

**Comment by MordFustang21** [comment]
Sorry, I should have been more specific yes you'd add it to the config.cson file.

**Comment by malkhamis** [comment]
that didn't seem to work despite trying to reload/close-reopen Atom after doing the suggested changes :(

**Comment by malkhamis** [comment]
The problem was resolved after updating my local gopls version to `master`
