### ISSUE TITLE
Recommended Atom gopls extension

### ISSUE THREAD

**Issue by stamblerre** [MordFustang21/ide-gopls#2]
Hi @MordFustang21! I just wanted to reach out because I linked this extension on the `gopls` [documentation page for Atom](https://github.com/golang/tools/blob/master/gopls/doc/atom.md), and I wanted to confirm that this is okay with you. I also wanted to ask if you'd be okay with me requesting that this extension be added to the list of language extensions on the `atom-languageclient` [wiki page](https://github.com/atom/atom-languageclient/wiki/List-of-Atom-packages-using-Atom-LanguageClient).

If you'd like to chat more directly, please feel free to reach out to me at rstambler@golang.org, or via the [Gophers Slack](https://invite.slack.golangbridge.org/).

**Comment by MordFustang21** [comment]
Yeah that's great. This was initially created as an experiment and I'm not sure how much time I'd be able to spend on it so most contributions/features would probably need to come from the community. I'm sure interest will probably slowly fade as Atom loses market share to other things like VSCode and GoLand.

**Comment by stamblerre** [comment]
Thanks! It seems solid as-is right now, but if something breaks, I'd be happy to jump in to investigate. Atom is definitely less popular, so this is pretty low stakes. Thank you for your work on this!
